name: annachhatra
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7+1
  path_provider: ^2.0.14
  provider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf

  assets:
     - images/Vector.png
     - images/logout_btn.png
     - images/hotel-green.png
     - images/hotel-marina.jpg
     - images/hotel-park.jpg
     - images/delete_icon.png

